FROM node:20-slim

WORKDIR /app

# Установка только необходимых зависимостей для разработки
COPY package*.json ./
RUN npm install

# Не копируем исходные файлы, они будут примонтированы
# при запуске контейнера

EXPOSE 5000

CMD ["npm", "run", "dev"] 