version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
    restart: unless-stopped